[pytest]
addopts = 
    -v
    --tb=short
    --strict-markers
    --alluredir=reports/allure-results
pythonpath = .

markers =
    smoke: marks tests as smoke
    regression: Mark tests as regression tests

# Use LambdaTest conftest
conftest = tests/conftest_lambdatest.py

